# Generated by Django 4.1.4 on 2023-01-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='postdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('titlesub', models.TextField()),
                ('postdate', models.TextField()),
                ('author_image', models.ImageField(upload_to='images')),
                ('postimage', models.ImageField(upload_to='images')),
                ('postcontent', models.TextField()),
            ],
        ),
    ]
