# Generated by Django 4.1.4 on 2023-01-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_sidepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdb',
            name='authorname',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
