# Generated by Django 4.1.4 on 2023-01-14 11:01

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_aboutme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdb',
            name='postdate',
            field=models.DateField(default=django.utils.datetime_safe.date.today),
        ),
    ]
