# Generated by Django 4.1.4 on 2023-01-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_alter_postdb_postdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidepost',
            name='dateside',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
