# Generated by Django 4.1.4 on 2023-01-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_alter_sidepost_dateside'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidepost',
            name='dateside',
            field=models.TextField(),
        ),
    ]
