# Generated by Django 4.1.4 on 2023-01-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_alter_sidepost_dateside'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidepost',
            name='story',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
